"""Structured inputs and outputs for the operations agent."""

from datetime import datetime

from pydantic import Field

from labos_copilot.domain import BlockerCategory, Severity
from labos_copilot.domain.base import DomainModel


class BriefItem(DomainModel):
    """One evidence-backed operations-brief item."""

    rule_id: str = Field(min_length=1)
    experiment_id: str = Field(min_length=1)
    category: BlockerCategory
    severity: Severity
    summary: str = Field(min_length=1)
    evidence: tuple[str, ...] = Field(min_length=1)
    recommended_action: str = Field(min_length=1)


class OperationsBrief(DomainModel):
    """Structured daily operations brief generated by the LLM."""

    generated_at: datetime
    experiments_reviewed: int = Field(ge=0)

    executive_summary: str = Field(min_length=1)
    critical_items: tuple[BriefItem, ...] = ()
    warning_items: tuple[BriefItem, ...] = ()
    healthy_experiment_ids: tuple[str, ...] = ()

    recommended_next_action: str = Field(min_length=1)


class OperationsNarrative(DomainModel):
    """LLM-generated narrative and priority selection."""

    executive_summary: str = Field(min_length=1)
    priority_experiment_id: str | None = None
    priority_rule_id: str | None = None


class AgentRunResult(DomainModel):
    """Validated result of one complete agent run."""

    question: str
    model_name: str
    brief: OperationsBrief
    tools_used: tuple[str, ...]
